org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.java.installations.auto-download=true

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Avoid Kotlin compile daemon crash on JDK GC auto-selection (Parallel GC)
kotlin.daemon.jvmargs=-XX:-UseParallelGC
