include(
	":app",
	":testutils",

	":features:mainhost",
	":features:home",
	":features:review",
	":features:cards",
	":features:constructor",
	":features:books",
	":features:words",
	":features:words:add",
	":features:words:detail",
	":features:materials",
	":features:profile",
	":features:authorization:signin",
	":features:authorization:signup",
	":features:dev:networkselection",

	":core:navigation",
	":core:network",
	":core:fakenetwork",
	":core:validation",
	":core:preferences",

	":shared:authorization",
	":shared:catalog",
	":shared:practice",
	":shared:converters:dateconverter",
	":shared:error",
	":shared:words:domain",

	":component:wui",
	":component:presentation",
)
