include(
	":app",
	":testutils",

	":features:mainhost",
	":features:home",
	":features:review",
	":features:cards:collection",
	":features:cards:training",
	":features:constructor:catalog",
	":features:constructor:practice",
	":features:books:library",
	":features:books:reader",
	":features:words:list",
	":features:materials",
	":features:profile",
	":features:authorization:signin",
	":features:authorization:signup",
	":features:dev:networkselection",

	":core:navigation",
	":core:network",
	":core:fakenetwork",
	":core:validation",
	":core:preferences",

	":shared:authorization",
	":shared:catalog",
	":shared:englishlevel",
	":shared:practice",
	":shared:converters:dateconverter",
	":shared:error",
	":shared:words:domain",

	":component:wui",
	":component:presentation",
)
